name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        # pass several variables to Cypress
        # both private (env) and public (expose)
        with:
          env: PASS_WORD=my-password
        env:
          # via process environment variables
          # private variable accessible via cy.env
          CYPRESS_API_KEY: '123secret!'
          # public variable accessible via Cypress.expose
          CYPRESS_EXPOSE_ANSWER: 42
          # since we cannot do --expose via Cypress github action
          # have to use the process environment variable
          CYPRESS_EXPOSE_USER_NAME: Joe
